[package]
name = "serde-nix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
thiserror = "1.0.25"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
